config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'rooms#index'
  resources :room_messages
  resources :rooms
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability # :nodoc:
  include CanCan::Ability

  def initialize(user)
    alias_action :create, :read, :update, :destroy, to: :crud

    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      can :read, RoomMessage
      can :crud, RoomMessage, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_messages, dependent: :destroy, inverse_of: :room
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room, inverse_of: :room_messages

  def as_json(options)
    super(options).merge(
      username: user.username, user_avatar_url: user.gravatar_url
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable
  validates :username, uniqueness: true, presence: true

  enum role: {
    admin: 0,
    sindicato: 1,
    suporte: 2
  }

  def gravatar_url
    gravatar_id = Digest::MD5.hexdigest(email).downcase
    "https://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username])
  end
end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController
  before_action :load_entities

  def create
    @room_message =
      RoomMessage.create(
        user: current_user,
        room: @room,
        message: params.dig(:room_message, :message)
      )
    RoomChannel.broadcast_to @room, @room_message
    head :ok
    authorize! :create, @room_message
  end

  protected

  def load_entities
    @room = Room.find params.dig(:room_message, :room_id)
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  before_action :load_room, only: %i[show edit update]
  before_action :load_rooms, only: %i[show]

  def index
    @rooms = Room.all
  end

  def show
    @room_message = RoomMessage.new room: @room
    @room_messages = @room.room_messages.includes(:user)
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      flash[:success] = "Room #{@room.name} created successfully"
      redirect_to rooms_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @room.update_attributes(room_params)
      flash[:success] = "Room #{@room.name} updated successfully"
    else
      render 'edit'
    end
  end

  protected

  def load_room
    @room = Room.find(params[:id]) if params[:id]
  end

  def load_rooms
    @rooms = Room.all
  end

  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper; end

app/helpers/room_messages_helper.rb
module RoomMessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{ content: "width=device-width, initial-scale=1, shrink-to-fit=no",
           name: "viewport"}
    %title RailsChatTutorial
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body.text-gray-800.bg-gray-600
    = render 'shared/navigation'
    .mt-2.mx-auto{:class => "md:w-10/12"}
      = yield

app/views/rooms/_form.html.haml
= form_for @room do |f|
  .field.mb-6
    = f.label :name,
      class: 'block text-gray-700 mb-1 font-bold'
    = f.text_field :name,
      class: 'shadow appearance-none rounded w-full border px-3 py-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'
  = f.submit 'Save', role: 'button',
    class: 'shadow bg-teal-700 hover:bg-teal-900 hover:shadow-xl focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded'

app/views/rooms/_rooms.html.haml
- if can? :create, Room
  = link_to 'Criar Sala', new_room_path, class: 'block m-1 p-2 text-white rounded bg-teal-700 hover:bg-teal-900 hover:shadow-xl'
- if @rooms.present?
  .bg-blue-100.border-aqua.p-2
    - @rooms.each do |room|
      .truncate
        = link_to room.name, room_path(room), class: 'inline-block bg-teal-600 hover:bg-teal-800 text-white mt-4 rounded px-2 py-1'
- else
  %p Não há salas disponíveis.

app/views/rooms/edit.html.haml
.px-4.mx-auto.py-4.m-1.rounded-lg.shadow-md.bg-white{:class => "md:w-3/4"}
  %h1.text-center.text-2xl.text-gray-600.font-bold.m-2
    Edit Room #{@room.name}
  = render 'form'

app/views/rooms/index.html.haml
.flex
  .px-2.py-2.m-1.rounded-lg.shadow-md.bg-white{:class => "w-1/4"}
    = render 'rooms'
  .px-4.py-2.m-1.rounded-lg.shadow-md.bg-white{:class => "w-3/4"}
    .bg-teal-100.h-full.text-teal-900.border-lg.rounded.p-2
      %h1.text-2xl.text-gray-600.font-bold Welcome to Rails Chat Tutorial
      %p.text-teal-500 We need to talk
      %hr/
      %p.text-teal-400 You can join a room or create a new room from the sidebar

app/views/rooms/new.html.haml
.px-4.mx-auto.py-4.m-1.rounded-lg.shadow-md.bg-white{:class => "md:w-3/4"}
  %h1.text-center.text-2xl.text-gray-600.font-bold.m-2 Create Room
  = render 'form'

app/views/rooms/show.html.haml
.flex
  .px-2.py-2.m-1.rounded-lg.shadow-md.bg-white{:class => "w-1/4"}
    = render 'rooms'
  .flex.flex-col{:class => "w-3/4"}
    .px-4.py-2.m-1.rounded-lg.shadow-md.bg-white
      .bg-teal-100.overflow-hidden.overflow-y-scroll.relative.h-full.w-full.text-teal-900.border-lg.rounded.p-2
        %h1.text-2xl.text-center.text-gray-800.font-bold= @room.name
        %hr/
        .chat{"data-channel-subscribe" => "room", "data-room-id" => "#{@room.id}"}
          - @room_messages.each do |room_message|
            .flex.items-center.m-2{"data-role" => "message-template"}
              .p-3.rounded-full.bg-teal-200
                %img.h-8.w-8.rounded-full.object-cover.object-fit{:alt => "Profile", :src => "#{room_message.user.gravatar_url}"}/
              .ml-1.w-full.p-2.rounded-lg.bg-teal-200.text-gray-900
                .text-sm.text-right
                  %small.uppercase.leading-tight.text-gray-600{"data-role" => "message-date"}= room_message.user.username
                .text-base.text-gray-800{"data-role" => "message-text"}= room_message.message
                .text-sm.text-right
                  %small.leading-tight.text-gray-600{"data-role" => "message-date"}= time_ago_in_words(room_message.created_at)
        %hr/
    .px-4.py-2.m-1.rounded-lg.shadow-md.bg-white
      = form_for @room_message,
        remote: true,
        data: { controller: 'room-message',
                action: 'ajax:success->room-message#onPostSuccess' },
                html: { class: 'w-full' } do |f|
        .flex.mb-1.w-full
          = f.text_field :message, autofocus: true, data: { target: 'room-message.message' }, class: 'w-full shadow appearance-none rounded border px-3 py-3 text-white  focus:outline-none focus:shadow-outline bg-gray-700 font-bold', placeholder: 'type you message....'
          = f.submit 'Send', class: 'shadow bg-teal-700 ml-auto hover:bg-teal-900 hover:shadow-xl focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded'
          = f.hidden_field :room_id, as: :hidden

app/views/shared/_navigation.html.haml
%body
  %header.bg-gray-800.text-white.p-2
    .flex.mx-auto.justify-between.items-center{:class => "w-10/12"}
      %div
        = link_to 'Chat Mondrian', root_url,                                       |
          class: 'font-bold text-gray-500 hover:text-white text-xl tracking-tight' |
      %div
        - if current_user
          .flex.justify-between.items-center
            %button.flex.items-center.text-white.text-xl.hover:font-bold{:role => "button"}
              %img.h-8.rounded-full{:alt => "", :src => "#{current_user.gravatar_url}"}/
              %span.ml-2= current_user.username
            = link_to 'Logout', destroy_user_session_path,                                              |
              method: :delete,                                                                          |
              class: 'inline-block bg-teal-700 hover:bg-teal-800 rounded-full px-4 py-2 ml-8 font-bold' |